import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import SideMenu from '@/components/SideMenu'
import { Outfit } from 'next/font/google'

const OutfitFont = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={OutfitFont.className}>
        <Navbar />
        <div className='flex'>
          <SideMenu  />
          {children}
        </div>
      </body>
    </html>
  )
}
